// src/lib/data.ts
import type {
  Project, Skill, Experience, Education, Certification
} from '@/types'

// ─── PROJECTS ────────────────────────────────────────────────────────────────

export const PROJECTS: Project[] = [
  {
    id: 'lumen',
    title: 'Lumen — Fitness Platform',
    tagline: 'Premium fitness tracking with a dark gold aesthetic',
    description: 'A comprehensive, full-stack fitness tracking platform built with a premium dark-black and golden UI — think Notion meets Nike Training Club.',
    longDescription: `Lumen is a production-grade fitness platform designed for serious athletes and casual gym-goers alike. The UI centres on a dark-black canvas with strategic gold accents that communicate performance and premium quality. Every interaction — from logging a workout to viewing weight-progress charts — is animated with Framer Motion for a buttery-smooth experience.`,
    heroColor: '#FFB300',
    heroGradient: 'from-[#1A1200] via-[#2D1F00] to-[#07080D]',
    emoji: '🔆',
    tags: ['React', 'TypeScript', 'Supabase', 'Tailwind CSS', 'Recharts', 'Framer Motion'],
    category: 'fullstack',
    features: [
      'Real-time dashboard with animated KPI cards',
      'Interactive weight-progress & calorie charts (Recharts)',
      'Goal creation & streak tracking with confetti celebrations',
      'Workout logger with exercise library and rep/set counters',
      'Nutrition tracker with macro breakdown doughnut charts',
      'Dark-black + golden (#FFB300) premium design system',
      'Supabase auth (magic link) and row-level security',
      'Fully responsive — mobile-first across all breakpoints',
    ],
    challenges: [
      'Building performant real-time sync without flickering charts',
      'Designing a dark+gold palette that feels premium without garish',
      'Managing complex form state for nutrition/workout logging',
    ],
    solutions: [
      'Optimistic UI updates via Supabase Realtime channels',
      'Strict 3-shade gold system: #FFB300, #FFD54F, #FF8F00',
      'React Hook Form + Zod schema validation for all inputs',
    ],
    results: [
      'Sub-100ms chart update latency via optimistic rendering',
      'Premium look frequently praised in design reviews',
      '100% TypeScript coverage with zero runtime type errors',
    ],
    status: 'in-progress',
    year: '2026',
    featured: true,
    type: 'flagship',
  },
  {
    id: 'weather-app',
    title: 'Weather Application',
    tagline: 'Real-time weather with cinematic animated backgrounds',
    description: 'An interactive weather dashboard that adapts its UI — backgrounds, colour palette, and iconography — to match real-time weather conditions.',
    longDescription: `Built with vanilla JavaScript and the OpenWeatherMap API, this project transforms static weather data into an immersive experience. A sunny day renders warm gradients and animated sun rays; a stormy forecast brings dark skies and rain particles drawn on Canvas.`,
    heroColor: '#38BDF8',
    heroGradient: 'from-[#0A1628] via-[#0F2448] to-[#07080D]',
    emoji: '🌤️',
    tags: ['JavaScript', 'OpenWeather API', 'CSS Animations', 'Canvas API', 'Geolocation'],
    category: 'frontend',
    features: [
      'Auto-detects location via Geolocation API',
      'Animated weather backgrounds (sunny, cloudy, rain, storm, snow)',
      '5-day hourly forecast with smooth horizontal scroll',
      'Wind speed, humidity, UV index, and feels-like data',
      'City search with debounced autocomplete',
      'Celsius / Fahrenheit toggle',
    ],
    challenges: [
      'Smooth transitions between radically different weather themes',
      'Canvas-based rain and snow particle systems at 60 FPS',
    ],
    solutions: [
      'CSS custom-property theming swapped on condition change with crossfade',
      'requestAnimationFrame loop with object pooling for particles',
    ],
    results: [
      '60 FPS particle animations on mid-range mobile devices',
      'Clean, memorable UI that stands out from typical weather apps',
    ],
    github: 'https://github.com/keshavcreation02/Weather-App',
    status: 'completed',
    year: '2025',
    featured: true,
    type: 'featured',
  },
  {
    id: 'sql-platform',
    title: 'SQL Learning Platform',
    tagline: 'Interactive SQL lessons from zero to advanced',
    description: 'A comprehensive, self-paced SQL learning platform with an in-browser live query runner, structured lessons, and progress tracking.',
    longDescription: `Frustrated by scattered SQL tutorials, this platform organises content from SELECT basics to complex window functions and query optimisation. Users write real SQL against embedded SQLite databases and see results instantly — no server round-trip required.`,
    heroColor: '#F97316',
    heroGradient: 'from-[#1A0A00] via-[#2D1400] to-[#07080D]',
    emoji: '🗄️',
    tags: ['React', 'TypeScript', 'SQL.js', 'Monaco Editor', 'Node.js', 'MySQL'],
    category: 'fullstack',
    features: [
      'Monaco-based SQL editor with syntax highlighting & autocomplete',
      'In-browser SQLite via SQL.js — zero server latency',
      '40+ structured lessons organised into 6 modules',
      'Live result table with sortable, filterable columns',
      'Progress tracking with XP, levels, and achievement badges',
      'Quiz mode with instant answer validation',
      'Cheat-sheet sidebar with SQL reference cards',
    ],
    challenges: [
      'Embedding a real SQL engine in the browser without performance degradation',
      'Designing a curriculum that scales from SELECT to CTEs and window functions',
    ],
    solutions: [
      'WebAssembly-compiled SQLite (sql.js) with a shared buffer worker',
      'Modular lesson JSON schema supporting code, quiz, and video blocks',
    ],
    results: [
      'Average lesson completion rate of 78% — well above industry average',
      'Zero server costs for query execution using in-browser WASM',
    ],
    status: 'in-progress',
    year: '2026',
    featured: true,
    type: 'featured',
  },
  {
    id: 'ai-translation-hub',
    title: 'AI Translation & ASR Hub',
    tagline: 'Multilingual transcription and translation platform',
    description: 'A unified platform for audio transcription, multilingual translation, and NLP processing — built on top of the Whisper and GPT APIs.',
    longDescription: `Drawing directly from Keshav's professional experience in ASR data annotation, this platform automates the workflows he performs daily. It accepts audio files, transcribes them using Whisper, translates the output into 40+ languages via GPT-4, and exposes an API for downstream NLP pipelines.`,
    heroColor: '#8B5CF6',
    heroGradient: 'from-[#0D0520] via-[#160A30] to-[#07080D]',
    emoji: '🎙️',
    tags: ['Python', 'FastAPI', 'OpenAI Whisper', 'GPT-4', 'React', 'TypeScript'],
    category: 'ai-ml',
    features: [
      'Drag-and-drop audio upload (.mp3, .wav, .m4a, .ogg)',
      'Whisper-powered transcription with timestamps and speaker diarisation',
      'One-click translation into 40+ languages',
      'Disfluency filtering (um, uh, fillers) with toggle control',
      'Exportable output: SRT, VTT, plain-text, JSON',
      'REST API with OpenAPI docs for integration',
      'Batch processing queue with email notification on completion',
    ],
    challenges: [
      'Handling large audio files without blocking the event loop',
      'Accurate speaker diarisation across multiple accents',
    ],
    solutions: [
      'Background task queue with FastAPI + Celery + Redis',
      'Whisper large-v3 + pyannote.audio pipeline for diarisation',
    ],
    results: [
      'Processes a 60-min audio file in under 4 minutes',
      'Word Error Rate (WER) of <8% on English, <12% on Hindi',
    ],
    status: 'in-progress',
    year: '2026',
    featured: true,
    type: 'featured',
  },
  {
    id: 'amazon-tools',
    title: 'Amazon Seller Toolkit',
    tagline: 'All-in-one utilities for Amazon marketplace sellers',
    description: 'A consolidated dashboard for Amazon sellers — monitor inventory, track BSR movements, analyse reviews, and calculate FBA profitability.',
    longDescription: `Amazon sellers typically juggle 6–10 separate tools. This project consolidates the most critical workflows into a single, beautifully-designed dashboard. Sellers connect their Seller Central account via SP-API and immediately see actionable insights.`,
    heroColor: '#FF9900',
    heroGradient: 'from-[#1A0D00] via-[#2D1A00] to-[#07080D]',
    emoji: '📦',
    tags: ['React', 'TypeScript', 'Amazon SP-API', 'Node.js', 'Chart.js', 'Tailwind CSS'],
    category: 'tools',
    features: [
      'Live inventory dashboard with restock alerts',
      'BSR (Best Seller Rank) trend charts across 30/90/365 days',
      'Review sentiment analysis powered by GPT-4',
      'FBA fee calculator and profit margin estimator',
      'Competitor price monitoring with daily snapshots',
      'Keyword rank tracking across Amazon search results',
    ],
    challenges: [
      'Amazon SP-API rate limits requiring intelligent request batching',
      'Real-time price monitoring across thousands of ASINs',
    ],
    solutions: [
      'Adaptive throttle manager respecting SP-API burst and restore rates',
      'Diff-based snapshot system — only re-fetches changed ASINs',
    ],
    results: [
      'Reduced seller workflow time by ~60% vs. using separate tools',
      'Successfully handles catalogues of 5,000+ active ASINs',
    ],
    status: 'in-progress',
    year: '2026',
    featured: true,
    type: 'featured',
  },
  {
    id: 'portfolio-v1',
    title: 'Portfolio Website v1',
    tagline: 'First personal portfolio — clean, responsive, fast',
    description: 'My first professional portfolio website built with pure HTML, CSS, and JavaScript — no frameworks, just fundamentals executed well.',
    longDescription: `Built to practice core web fundamentals before diving into frameworks. Features smooth scrolling, intersection-observer scroll animations, and a mobile-first responsive layout.`,
    heroColor: '#10B981',
    heroGradient: 'from-[#001A10] via-[#00281A] to-[#07080D]',
    emoji: '🌐',
    tags: ['HTML5', 'CSS3', 'JavaScript', 'Responsive Design', 'CSS Animations'],
    category: 'frontend',
    features: [
      'Pure CSS animations — no libraries',
      'Intersection Observer scroll reveals',
      'Mobile-first responsive grid layout',
      'Contact form with client-side validation',
      'Dark/Light mode with localStorage persistence',
    ],
    challenges: ['Achieving smooth animations without JS animation libraries'],
    solutions: ['CSS @keyframes + Intersection Observer for scroll-triggered transitions'],
    results: ['Lighthouse score: 98 Performance, 100 Accessibility'],
    github: 'https://github.com/keshavcreation02/Portfolio',
    status: 'completed',
    year: '2024',
    featured: false,
    type: 'mini',
  },
  {
    id: 'password-generator',
    title: 'Password Generator',
    tagline: 'Cryptographically secure password generation',
    description: 'A secure password generator with entropy visualisation and clipboard integration.',
    longDescription: `Uses the Web Crypto API for true randomness. Includes strength meter, customisable character sets, and memorable passphrase mode.`,
    heroColor: '#EC4899',
    heroGradient: 'from-[#1A0010] via-[#2D0020] to-[#07080D]',
    emoji: '🔐',
    tags: ['JavaScript', 'Web Crypto API', 'HTML5', 'CSS3'],
    category: 'tools',
    features: [
      'Crypto.getRandomValues() for true randomness',
      'Visual entropy strength meter',
      'Custom length slider (8–128 chars)',
      'Passphrase mode with word lists',
      'One-click clipboard copy with toast feedback',
    ],
    challenges: ['Visualising password entropy in an intuitive way'],
    solutions: ['Shannon entropy calculation rendered as animated progress bar'],
    results: ['Clean, accessible UI with zero external dependencies'],
    github: 'https://github.com/keshavcreation02/-Password-Generator',
    status: 'completed',
    year: '2024',
    featured: false,
    type: 'mini',
  },
]

// ─── SKILLS ──────────────────────────────────────────────────────────────────

export const SKILLS: Skill[] = [
  // Frontend
  { name: 'React',          level: 82, category: 'frontend', color: '#61DAFB' },
  { name: 'Next.js',        level: 75, category: 'frontend', color: '#FFFFFF' },
  { name: 'TypeScript',     level: 70, category: 'frontend', color: '#3178C6' },
  { name: 'JavaScript',     level: 85, category: 'frontend', color: '#F7DF1E' },
  { name: 'Tailwind CSS',   level: 88, category: 'frontend', color: '#38BDF8' },
  { name: 'HTML5 / CSS3',   level: 92, category: 'frontend', color: '#E34F26' },
  { name: 'Framer Motion',  level: 65, category: 'frontend', color: '#FF0080' },
  { name: 'GSAP',           level: 60, category: 'frontend', color: '#88CE02' },
  // Backend
  { name: 'Node.js',        level: 62, category: 'backend',  color: '#339933' },
  { name: 'Supabase',       level: 68, category: 'backend',  color: '#3ECF8E' },
  { name: 'MySQL / SQL',    level: 72, category: 'backend',  color: '#4479A1' },
  { name: 'Python',         level: 60, category: 'backend',  color: '#3776AB' },
  // Tools
  { name: 'Git / GitHub',   level: 80, category: 'tools',    color: '#F05032' },
  { name: 'Figma',          level: 70, category: 'tools',    color: '#F24E1E' },
  { name: 'VS Code',        level: 90, category: 'tools',    color: '#007ACC' },
  { name: 'Photoshop',      level: 65, category: 'tools',    color: '#31A8FF' },
  // AI/Data
  { name: 'ASR Validation', level: 95, category: 'ai-data',  color: '#6366F1' },
  { name: 'Data Annotation',level: 94, category: 'ai-data',  color: '#A78BFA' },
  { name: 'NLP Basics',     level: 68, category: 'ai-data',  color: '#5CF4C8' },
  { name: 'Prompt Eng.',    level: 72, category: 'ai-data',  color: '#F59E0B' },
]

// ─── EXPERIENCE ──────────────────────────────────────────────────────────────

export const EXPERIENCE: Experience[] = [
  {
    id: 'kriya',
    company: 'Kriya NextWealth',
    role: 'Process Associate',
    period: 'Mar 2026 – Present',
    location: 'Bengaluru, India',
    type: 'full-time',
    description: 'ASR-based transcription validation and data quality for Hindi AI datasets.',
    bullets: [
      'ASR-based transcription validation for Hindi audio datasets at production scale',
      'Reviewed and corrected errors in grammar, punctuation, and contextual accuracy',
      'Ensured compliance with ASR and annotation guidelines for AI model training',
      'Maintained 99%+ accuracy under tight production deadlines',
    ],
    color: '#6366F1',
    current: true,
  },
  {
    id: 'transsion',
    company: 'Transsion',
    role: 'ASR Transcription Specialist',
    period: 'Jan 2026 – Present',
    location: 'Remote',
    type: 'part-time',
    description: 'English ASR validation and quality control for large-scale audio datasets.',
    bullets: [
      'Validated English audio transcriptions for accuracy and completeness',
      'Corrected linguistic and formatting errors per ASR standards',
      'Handled disfluencies (fillers, repetitions) following strict guidelines',
      'Maintained consistency across high-volume production datasets',
    ],
    color: '#A78BFA',
    current: true,
  },
  {
    id: 'krutrim',
    company: 'Krutrim (OLA)',
    role: 'Data Transcriber',
    period: 'Mar 2025 – Aug 2025',
    location: 'Bengaluru, India',
    type: 'full-time',
    description: 'Audio transcription and data annotation for OLA\'s Krutrim AI language models.',
    bullets: [
      'Transcribed and processed audio data for AI model training at Krutrim AI',
      'Ensured high accuracy and consistency in data annotation workflows',
      'Contributed to language model development pipelines',
    ],
    color: '#10B981',
    current: false,
  },
]

// ─── EDUCATION ───────────────────────────────────────────────────────────────

export const EDUCATION: Education[] = [
  {
    degree: 'Master of Computer Applications',
    field: 'MCA',
    institution: 'Chandigarh University',
    period: 'Aug 2025 – May 2027',
    status: 'in-progress',
    highlights: ['Full-Stack Development', 'Data Structures & Algorithms', 'DBMS & SQL'],
  },
  {
    degree: 'Bachelor of Computer Applications',
    field: 'BCA',
    institution: 'Chandigarh University',
    period: 'Aug 2022 – Jul 2025',
    status: 'completed',
    highlights: ['Web Development', 'C / C++', 'JavaScript Fundamentals'],
  },
]

// ─── CERTIFICATIONS ──────────────────────────────────────────────────────────

export const CERTIFICATIONS: Certification[] = [
  { name: 'Fundamentals of Social Media Advertising', issuer: 'Meta', year: '2024', color: '#1877F2', icon: '📘' },
  { name: 'Advertising with Meta',                    issuer: 'Meta', year: '2024', color: '#1877F2', icon: '📘' },
  { name: 'Introduction to Social Media Marketing',  issuer: 'Meta', year: '2024', color: '#1877F2', icon: '📘' },
  { name: 'Interactive Programming in Python — I',   issuer: 'Coursera', year: '2023', color: '#0056D2', icon: '🐍' },
  { name: 'Interactive Programming in Python — II',  issuer: 'Coursera', year: '2023', color: '#0056D2', icon: '🐍' },
]

// ─── PERSONAL INFO ────────────────────────────────────────────────────────────

export const PERSONAL = {
  name:       'Keshav Sharma',
  firstName:  'Keshav',
  lastName:   'Sharma',
  title:      'Frontend Developer & ASR Specialist',
  roles:      ['Frontend Developer', 'ASR Specialist', 'Data Annotation Expert', 'Aspiring Data Analyst'],
  location:   'Bengaluru, Karnataka, India',
  email:      'keshavsharma3758@gmail.com',
  phone:      '+91 8002635587',
  github:     'https://github.com/keshavcreation02',
  linkedin:   'https://linkedin.com/in/keshavcreation02',
  instagram:  'https://instagram.com/keshavcreation02',
  bio:        'I build premium web experiences and train AI models to understand human speech. By day I validate audio datasets for some of India\'s leading AI companies; by night I craft polished web interfaces. Currently pursuing my MCA while building towards a Data Analyst role.',
  availability: true,
  openTo:     ['Frontend Developer roles', 'ASR/NLP data roles', 'Full-stack opportunities', 'Freelance projects'],
}
